server:
  port: 8089
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    address: mysql:3306
    database: canal_manager
    username: canal_manager
    password: canal_manager
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${spring.datasource.address}/${spring.datasource.database}?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    hikari:
      maximum-pool-size: 30
      minimum-idle: 1

canal:
  adminUser: admin
  adminPasswd: 123456